"""empty message

Revision ID: bb6aab92f658
Revises: 70e352b66dd2
Create Date: 2021-12-16 19:09:43.334152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6aab92f658'
down_revision = '70e352b66dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('coverPhoto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'coverPhoto')
    # ### end Alembic commands ###
