"""empty message

Revision ID: a4dd61f73212
Revises: bb6aab92f658
Create Date: 2021-12-16 19:46:03.123855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dd61f73212'
down_revision = 'bb6aab92f658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    # ### end Alembic commands ###
