"""empty message

Revision ID: 70e352b66dd2
Revises: d3e309f38cd5
Create Date: 2021-12-16 15:09:50.667389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e352b66dd2'
down_revision = 'd3e309f38cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], name='favorite_projectId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='favorite_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
