"""empty message

Revision ID: d3779719ae9c
Revises: 70e352b66dd2
Create Date: 2022-01-25 14:40:27.811383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3779719ae9c'
down_revision = '70e352b66dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user')
    op.add_column('users', sa.Column('profilePic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    op.add_column('comments', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
